version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # Log into Amazon ECR
      echo Logging in to Amazon ECR...
      $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      # Build the Docker image and tag it
      echo Building Docker image...
      docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      # Push the Docker image to ECR
      echo Pushing Docker image to ECR...
      docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      # Generate image definitions for ECS deployment
      echo Generating imagedefinitions.json...
      printf '[{"name":"my-app-container","imageUri":"%s.dkr.ecr.%s.amazonaws.com/%s:%s"}]' $AWS_ACCOUNT_ID $AWS_DEFAULT_REGION $ECR_REPOSITORY $CODEBUILD_RESOLVED_SOURCE_VERSION > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
